name: Build Latest

on:
  push:
    branches: 
      - '*'
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  appimage:
    name: Build
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    strategy:
      matrix:
        include:
          - container: ghcr.io/viam-modules/csi-camera/viam-cpp-base-jetson:0.0.4
            TARGET: jetson
            META_PATH: meta.json
          - container: ghcr.io/viam-modules/csi-camera/viam-cpp-base-pi:0.0.4
            TARGET: pi
            META_PATH: meta-pi.json
    container:
      image: ${{ matrix.container }}
      options: --platform linux/arm64

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "TARGET=${{ matrix.TARGET }}" >> $GITHUB_ENV
          echo "META_PATH=${{ matrix.META_PATH }}" >> $GITHUB_ENV

      - name: Clean build artifacts
        run: make clean

      - name: Install module dependencies
        run: make dep

      - name: Build viam-csi binary
        run: make build

      - name: Build viam-csi appimage
        run: make package
